name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Ensure Bun is found by adding its install directory to PATH
      PATH: ${{ secrets.HOME }}/.bun/bin:$PATH
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "Bun installed to $HOME/.bun/bin"
        shell: bash

      - name: Install dependencies
        run: bun install
        shell: bash

      - name: Run tests
        run: bun test --coverage
        shell: bash